#!/usr/bin/env python3
"""116 final zero-move A/B: the tree as it stands against ``HEAD``, not itself.

`tools/116_zero_move.py` proves the *current* code has not moved since this
batch's before-baseline. That is necessary and not sufficient: the master wants
the five existing grammars compared against the revision that shipped them, so
the two sides are generated by two different *routers* — the one in the working
tree and the one in ``git show HEAD:src/boardwise/engines/router.py``.

Why the router and not ``drawcompiler``: 116 added the order-consumption pass to
``drawcompiler.py`` and this batch's follow-up changed ``router.py`` (Dijkstra ->
A*, plus two per-call memos). The A* change is the one that could silently
**reroute a wire** — a different optimal path through a tie — and a wire is a
picture, so the evidence has to be the pictures. 116's own drawcompiler work is
already covered by the 83-preview before/after pair, and this tool reproduces
it independently by running the *same* previews through both routers.

    .venv/Scripts/python.exe tools/116_ab_head.py
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY = ROOT / ".venv" / "Scripts" / "python.exe"
ROUTER = ROOT / "src" / "boardwise" / "engines" / "router.py"
SCRATCH = ROOT / "outputs" / "116"

TOOLS = ("053b_previews", "056_previews", "088_previews", "088b_previews",
         "098_previews")

INSTRUMENT = '''\
import hashlib, os, sys
sys.path.insert(0, %(src)r)
sys.path.insert(0, %(tests)r)
from boardwise.engines import router as rt
RECORD = os.environ["AB_PROBE"]
print("ROUTER_SHA " + hashlib.sha256(
    open(rt.__file__, "rb").read()).hexdigest())
'''


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate(tag: str) -> dict[str, str]:
    """Run all five preview generators, return ``relative path -> sha256``."""
    out = SCRATCH / f"ab_{tag}"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    digests: dict[str, str] = {}
    for tool in TOOLS:
        target = out / tool
        target.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            [str(PY), str(ROOT / "tools" / f"{tool}.py"), str(target)],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            cwd=ROOT,
        )
        if result.returncode != 0:
            sys.stderr.write(f"{tool} failed\n" + result.stdout[-1500:]
                             + result.stderr[-2500:])
            raise SystemExit(result.returncode)
        for file in sorted(target.rglob("*")):
            if file.is_file():
                digests[f"{tool}/{file.relative_to(target).as_posix()}"] = (
                    _sha(file))
    return digests


def main() -> int:
    SCRATCH.mkdir(parents=True, exist_ok=True)
    before = _sha(ROUTER)
    head = subprocess.run(
        ["git", "show", "HEAD:src/boardwise/engines/router.py"],
        capture_output=True, cwd=ROOT,
    )
    if head.returncode != 0:
        sys.stderr.write("could not read the committed router\n")
        return 2
    if head.stdout == ROUTER.read_bytes():
        sys.stderr.write(
            "the working tree router is already HEAD's; there is nothing to "
            "A/B. This tool compares the two routers, not two revisions of the "
            "drawcompiler.\n")
        return 2

    backup = ROUTER.read_bytes()
    scratch = Path(tempfile.mkdtemp(prefix="ab_", dir=str(SCRATCH)))
    try:
        ROUTER.write_bytes(head.stdout)
        old = generate("head")
        ROUTER.write_bytes(backup)
        new = generate("tree")
    finally:
        ROUTER.write_bytes(backup)

    print(f"router sha256  HEAD {hashlib.sha256(head.stdout).hexdigest()}")
    print(f"router sha256 tree {before}")
    print(f"\n{len(old)} artefacts regenerated on each side")
    changed = [name for name in sorted(old) if old[name] != new.get(name)]
    missing = [name for name in sorted(old) if name not in new]
    extra = [name for name in sorted(new) if name not in old]
    print(f"changed {len(changed)}   missing {len(missing)}   extra {len(extra)}")
    for name in changed:
        print(f"  CHANGED {name}")
    for name in missing:
        print(f"  MISSING {name}")
    for name in extra:
        print(f"  EXTRA   {name}")
    (SCRATCH / "ab_head_vs_tree.txt").write_text(
        "\n".join(f"{old[n]} *{n}" for n in sorted(old)) + "\n", encoding="utf-8")
    if backup != ROUTER.read_bytes():
        sys.stderr.write("the router was not restored\n")
        return 1
    print(f"\nrouter restored byte-identical: {_sha(ROUTER) == before}")
    return 1 if (changed or missing or extra) else 0


if __name__ == "__main__":
    raise SystemExit(main())
